version: '3.8'

services:
  app:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "${APP_PORT:-3000}:3000"
    depends_on:
      - db

  db:
    image: postgres:14.2
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"

volumes:
  data:
